// generated by cds-compiler version 3.5.4 
@cds.persistence.exists : true
@title : 'Available objects'
entity SYS.OBJECTS {
  @title : 'Object category of the object (default = null)'
  OBJECT_CATEGORY : String(1);
  @title : 'Schema name of the object'
  SCHEMA_NAME : String(256);
  @title : 'Object name'
  OBJECT_NAME : String(256);
  @title : 'Object type'
  OBJECT_TYPE : String(32);
  @title : 'Object ID'
  OBJECT_OID : Integer64;
};

